version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      #DJANGO_SETTINGS_MODULE: "kmi-yinfs.settings"
      PG_USER: postgres
      PG_PASSWORD: postgrespw
      PG_HOST: db
      PG_PORT: 5432
      PG_DB_NAME: postgres
      #PG_DB_ARGS: TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'cs_CZ.UTF-8' LC_CTYPE 'cs_CZ.UTF-8'
    volumes:
      - ./app/:/app/
    depends_on:
      - db
    ports:
      - "8000:8000"
